dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
  MRL: True
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 32
  dataset_path: ImageNet22k:root=TRAIN:root=/lustre/fsmisc/dataset/ImageNet21K/winter21_whole/:extra=/lustre/fsn1/projects/rech/yic/uco38ei/ImNet_22k_dinov2/
  centering: sinkhorn_knopp
  use_block_masking: True
  use_inverse_block: True
  roll: True
  high_resolution_finetune: False
student:
  arch: vit_large
  patch_size: 16
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 100
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 10
  layerwise_decay: 1.0
crops:
  local_crops_size: 96
  global_crops_size: 224
